---
title: "shiny-tuto"
author: "Eduardo Elias Ribeiro Junior"
output:
  html_document:
    toc: false
    theme: flatly
    keep_md: true
---

Utilização básica do pacote **shiny** para criação de aplicativos web
com R. Este material foi elaborado inicialmente para apresentação no
evento [meetup - useR-SP][meetup], realizado em 09 de outubro de 2015.
Mas está sujeito a atualização, pois pretende ser um guia inicial para
aprendizado **shiny**. A versão utilizada na apresentação está
disponível em [link][meetupedu].

O repositório está estruturado da seguinte forma:

O diretório `apps` é responsável por armazenar os subdiretórios das
aplicações em **shiny** elaboradas (aqui estão os códidos fonte, `ui.R`
e `server.R`), o diretório `images` armazena as images utilizadas para 
explicação e finalmente os slides apresentados no evento são resultados 
da compilação do arquivo `shiny-pres.Rmd`. Porém como esta apresentação 
contém resultados **shiny**, sua visualização será possível a partir de 
`rmarkdown::run("shiny-pres.Rmd")`.

```{r, engine = "sh", echo = FALSE}
tree
```

[meetup]: www.meetup.com/pt/useR-SP/
[meetupedu]: www.pet.est.ufpr.br/meetupshiny

